# Generated by Django 4.1.7 on 2023-05-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0001_initial'),
        ('rentals', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StationComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complaints.complaint')),
                ('locker_number', models.SmallIntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_complaint', to='stations.station')),
            ],
            bases=('complaints.complaint',),
        ),
        migrations.CreateModel(
            name='RentalComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complaints.complaint')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rental_complaint', to='rentals.rental')),
            ],
            bases=('complaints.complaint',),
        ),
        migrations.CreateModel(
            name='BicycleComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complaints.complaint')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle_complaint', to='bicycles.bicycle')),
            ],
            bases=('complaints.complaint',),
        ),
    ]
