# Generated by Django 4.1.7 on 2023-05-11 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_per_unit', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnetic_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('liquidated', 'Liquidated')], default='good', max_length=20)),
                ('bicycle_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicycles.bicyclestock')),
            ],
        ),
    ]
