# Generated by Django 4.1.7 on 2023-05-07 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_per_unit', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='bicycle',
            name='magnetic_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('liquidated', 'Liquidated')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='bicycle_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicycles.bicyclestock'),
        ),
    ]
