# Generated by Django 4.1.7 on 2023-05-13 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('using', 'Using'), ('finished', 'Finished'), ('overtime', 'Overtime')], default='using', max_length=50)),
                ('time_begin', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('is_violated', models.BooleanField(default=False)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle_rental', to='bicycles.bicycle')),
                ('end_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_station_rental', to='stations.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_station_rental', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rental', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
