# Generated by Django 4.1.7 on 2023-05-08 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_alter_locker_bicycle'),
        ('bicycles', '0002_bicyclestock_bicycle_magnetic_key_bicycle_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait_for_comfirm', 'Wait for comfirm'), ('canceled', 'Canceled'), ('using', 'Using'), ('finished', 'Finished'), ('overtime', 'Overtime')], default='wait_for_comfirm', max_length=50)),
                ('time_begin', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(default='')),
                ('bicycle', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle_rental', to='bicycles.bicycle')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_station_rental', to='stations.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_station_rental', to='stations.station')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rental', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
