# Generated by Django 4.1.7 on 2023-05-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait_for_comfirm', 'Wait for comfirm'), ('canceled', 'Canceled'), ('using', 'Using'), ('finished', 'Finished'), ('overtime', 'Overtime')], default='wait_for_comfirm', max_length=50)),
                ('time_begin', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('is_violated', models.BooleanField(default=False)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle_rental', to='bicycles.bicycle')),
                ('end_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_station_rental', to='stations.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_station_rental', to='stations.station')),
            ],
        ),
    ]
