# Generated by Django 4.1.7 on 2023-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='time_end',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
