# Generated by Django 4.1.7 on 2023-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_violated',
            field=models.BooleanField(default=False),
        ),
    ]
