# Generated by Django 4.1.7 on 2023-05-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_locker_bicycle'),
        ('bicycles', '0003_alter_bicyclestock_description'),
        ('rentals', '0003_rental_is_violated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station_Complaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentals.complaint')),
                ('locker_number', models.SmallIntegerField(null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_complaint', to='stations.station')),
            ],
            bases=('rentals.complaint',),
        ),
        migrations.CreateModel(
            name='Rental_Complaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentals.complaint')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rental_complaint', to='rentals.rental')),
            ],
            bases=('rentals.complaint',),
        ),
        migrations.CreateModel(
            name='Bicyle_Complaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentals.complaint')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle_complaint', to='bicycles.bicycle')),
            ],
            bases=('rentals.complaint',),
        ),
    ]
