# Generated by Django 4.1.7 on 2023-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_complaint_station_complaint_rental_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
