# Generated by Django 4.1.7 on 2023-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0003_alter_bicyclestock_description'),
        ('rentals', '0006_alter_complaint_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bicyle_Complaint',
            new_name='Bicycle_Complaint',
        ),
    ]
