# Generated by Django 4.1.7 on 2023-05-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_locker_bicycle'),
        ('bicycles', '0003_alter_bicyclestock_description'),
        ('rentals', '0007_rename_bicyle_complaint_bicycle_complaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bicycle_Complaint',
            new_name='BicycleComplaint',
        ),
        migrations.RenameModel(
            old_name='Rental_Complaint',
            new_name='RentalComplaint',
        ),
        migrations.RenameModel(
            old_name='Station_Complaint',
            new_name='StationComplaint',
        ),
    ]
