# Generated by Django 4.1.7 on 2023-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rename_bicycle_complaint_bicyclecomplaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcomplaint',
            name='complaint_ptr',
        ),
        migrations.RemoveField(
            model_name='rentalcomplaint',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='stationcomplaint',
            name='complaint_ptr',
        ),
        migrations.RemoveField(
            model_name='stationcomplaint',
            name='station',
        ),
        migrations.DeleteModel(
            name='BicycleComplaint',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='RentalComplaint',
        ),
        migrations.DeleteModel(
            name='StationComplaint',
        ),
    ]
