# Generated by Django 4.1.7 on 2023-05-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_locker_bicycle'),
        ('rentals', '0010_alter_rental_end_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_station_rental', to='stations.station'),
        ),
    ]
