# Generated by Django 4.1.7 on 2023-05-08 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_alter_rental_end_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='time_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
