# Generated by Django 4.1.7 on 2023-05-08 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0003_alter_bicyclestock_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0012_alter_rental_time_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='bicycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bicycle_rental', to='bicycles.bicycle'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='time_begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rental', to=settings.AUTH_USER_MODEL),
        ),
    ]
