# Generated by Django 4.1.7 on 2023-06-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_fcmtoken_fcm_token_alter_fcmtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='fcm_token',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
