# Generated by Django 4.1.7 on 2023-06-05 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fcmtoken_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='fcm_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcmtoken', to=settings.AUTH_USER_MODEL),
        ),
    ]
