# Generated by Django 4.1.7 on 2023-05-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
