# Generated by Django 4.1.7 on 2023-05-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
        ('stations', '0002_alter_locker_station_alter_station_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='bicycle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='bicycles.bicycle'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockers', to='stations.station'),
        ),
    ]
