# Generated by Django 4.1.7 on 2023-05-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_bicyclestock_bicycle_magnetic_key_bicycle_status_and_more'),
        ('stations', '0003_locker_bicycle_alter_locker_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='bicycle',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='bicycles.bicycle'),
        ),
    ]
