# Generated by Django 4.1.7 on 2023-05-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_bicyclestock_bicycle_magnetic_key_bicycle_status_and_more'),
        ('stations', '0004_alter_locker_bicycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='bicycle',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike', to='bicycles.bicycle'),
        ),
    ]
